### ISSUE TITLE
Uncaught TypeError: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by 2metres** [t9md/atom-project-find-navigation#1]
1. Search for something with multiple instances in one file
2. Click on the file name
3. Atom Throws err

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [project-find-navigation](https://github.com/t9md/atom-project-find-navigation) package, v0.0.4
### Stack Trace

Uncaught TypeError: Cannot read property 'range' of undefined

```
At /Users/andrew/.atom/packages/project-find-navigation/lib/main.coffee:99

TypeError: Cannot read property 'range' of undefined
  at Object.module.exports.confirm (/Users/andrew/.atom/packages/project-find-navigation/lib/main.coffee:99:23)
  at space-pen-li.<anonymous> (/Users/andrew/.atom/packages/project-find-navigation/lib/main.coffee:74:10)
  at space-pen-ol.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ol.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -4:04.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -4:03.6.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:02.5.0 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -4:02.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -4:01.2.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:00.7.0 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:26.3.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:10 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:09.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-toychest.theme-one-dark-ui)
     -0:26.3.0 project-find:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-toychest.theme-one-dark-ui)
     -0:23.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.7.0 project-find:show (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:11.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:11 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.3.0 core:move-down (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-csslint",
      "webbox-color",
      "atom-color-highlight",
      "toolbar-basic",
      "tool-bar-main",
      "tool-bar",
      "flex-tool-bar",
      "linter-scss-lint",
      "linter-haml",
      "subword-navigation"
    ],
    "ignoredNames": [
      "*.log"
    ],
    "themes": [
      "one-dark-ui",
      "atom-toychest"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
Sublime-Style-Column-Selection, v1.3.0
atom-toychest, v0.3.0
change-case, v0.6.0
color-picker, v2.0.11
html2haml, v0.10.0
language-cjsx, v0.3.0
language-dotenv, v1.0.0
language-ejs, v0.2.0
language-haml, v0.21.0
language-jade, v0.5.1
language-liquid, v0.4.0
line-ending-converter, v1.2.0
linter, v1.2.4
linter-clojure, v0.0.5
linter-js-yaml, v1.1.1
linter-jshint, v1.1.4
linter-jsonlint, v0.1.4
linter-ruby, v0.1.6
pain-split, v1.4.0
pigments, v0.9.0
pretty-json, v0.4.1
project-find-navigation, v0.0.4
tab-control, v0.6.7
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by t9md** [comment]
Thanks for reporting.
